### ISSUE TITLE
Glitches in emulated games

### ISSUE THREAD

**Issue by ghost** [nowrep/obs-vkcapture#163] opened 2023-09-10 17:47 UTC
I use obs-vkcapture/obs-gamecapture on Arch to record emulated games sometimes. For emulation I typically add the appimage to Steam as a non-Steam game, and use the launch option from there.
In this case it is RMG (popular custom Mupen64 client) most of the games I try to record (Both Banjo games, Donkey Kong, etc) end up like this when using Game Capture:
![Screenshot from 2023-09-10 12-30-50](https://github.com/nowrep/obs-vkcapture/assets/144619092/fee133ba-51c5-44e3-b644-0b3c657c1b74)
Yet they look normal using Window Capture:
![Screenshot from 2023-09-10 12-31-19](https://github.com/nowrep/obs-vkcapture/assets/144619092/bb37d05d-5ffa-4c7e-a6e0-61db19783d38)
The frames get all jumbled in the resulting recording, it does not happen on my screen when playing only in the recording. Not all games have these issues, I was able to fully record Super Mario 64 from Game Capture, but for some games I must use Window Capture or I get these glitches. I cannot find the source of the issue, the logs show nothing out of the ordinary

**Comment by nowrep** [comment] 2024-02-05 16:47
Closing as I can't reproduce and reporter is ghost.

**Closed by nowrep** 2024-02-05 16:47 UTC
Labels: gl
